[package]
name = "indk-proto"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
uuid  = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
